version: '3'

volumes:
  hubbub_codetest_project_local_postgres_data: {}
  hubbub_codetest_project_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: hubbub_codetest_project_local_django
    container_name: hubbub_codetest_project_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    image: postgres:14
    container_name: hubbub_codetest_project_local_postgres
    volumes:
      - hubbub_codetest_project_local_postgres_data:/var/lib/postgresql/data
      - hubbub_codetest_project_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
