# Generated by Django 4.1.9 on 2023-05-17 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ("modified", models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectPledge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ("modified", models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=5)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="giving.project")),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
