# Generated by Django 4.1.9 on 2023-05-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("giving", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpledge",
            name="pledgee",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
