# Generated by Django 4.1.9 on 2023-05-19 08:14
import random
from django.db import migrations
from django.utils.text import slugify

PROJECT_DESCRIPTION = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dignissim, justo nec mollis porttitor, est lacus pharetra massa, vel viverra enim tortor non risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam in nisi auctor nunc ultricies placerat. Duis sit amet mauris fermentum, vulputate nulla ut, mollis ligula. Fusce congue, erat quis pulvinar hendrerit, ante lorem cursus mi, ullamcorper efficitur elit est gravida enim. Vivamus ultrices dolor at quam sodales, in vulputate felis ullamcorper. Vivamus vel tincidunt justo. Donec pharetra nunc sodales libero tincidunt mattis. Nunc sagittis ex vel dictum suscipit. Morbi cursus dolor posuere, cursus turpis sed, blandit augue. Donec imperdiet erat dolor.

Vivamus nec libero laoreet sapien laoreet bibendum. Vestibulum vitae odio a elit imperdiet rutrum sit amet nec ante. Aliquam scelerisque, lacus at facilisis scelerisque, ipsum dui accumsan leo, non scelerisque erat augue vel massa. Integer rhoncus, est eget congue bibendum, sem ex vehicula ipsum, non pharetra nulla elit nec est. Nulla a mi vitae ligula condimentum iaculis. Phasellus sed tellus elit. Aenean bibendum, ipsum at ornare tristique, ex nisi gravida urna, ut dapibus purus metus eget purus. Sed semper urna metus, nec mattis lectus vulputate tempor. Fusce a justo eget massa egestas pulvinar vel eu justo. Donec quis ligula sit amet neque varius efficitur sed at sem. Proin rhoncus sem porta, rhoncus ligula ut, aliquet dolor. Integer malesuada malesuada urna sit amet fermentum. Donec id metus sit amet magna imperdiet eleifend at ut urna. Quisque eget libero eu dolor vehicula bibendum quis at diam. Nullam hendrerit, dolor non posuere semper, ex tortor luctus tortor, vitae pulvinar libero ex vel mauris. Ut dignissim quam id leo porta vehicula ac sed ipsum.
"""


def load_initial_data(apps, schema_editor):
    HOUSE_CHOICES = (
        "Gryffindor",
        "Hufflepuff",
        "Ravenclaw",
        "Slytherin",
    )

    project = apps.get_model("giving", "Project")
    project_pledge = apps.get_model("giving", "ProjectPledge")
    for name in ("Scholarship fund", "Student support", "Bursary fund"):
        p = project.objects.create(title=name, description=PROJECT_DESCRIPTION, slug=slugify(name))
        for x in range(random.randint(6, 157)):
            project_pledge.objects.create(
                project=p,
                amount=random.randint(100, 1000),
                house_choices=random.choice(HOUSE_CHOICES),
                pledgee=f"Pledger {x}",
            )


class Migration(migrations.Migration):
    dependencies = [
        ("giving", "0003_projectpledge_house_choices"),
    ]

    operations = [migrations.RunPython(load_initial_data)]
